### ISSUE TITLE
Use the built in Subscription instead of our own

### ISSUE THREAD

**Issue by myobie** [shareup/sqlite#11]
/cc @atdrendel

**Comment by atdrendel** [comment]
I'm closing this because we're now using a combination of [`SQLiteDatabaseChangePublisher`](https://github.com/shareup/sqlite/blob/main/Sources/SQLite/SQLiteDatabaseChangePublisher.swift), [`SQLiteResultsPublisher`](https://github.com/shareup/sqlite/blob/main/Sources/SQLite/SQLiteResultsPublisher.swift), and [`SQLiteFuture`](https://github.com/shareup/sqlite/blob/main/Sources/SQLite/SQLiteFuture.swift) to handle all of our Combine publishing needs.
